<Project Sdk="Godot.NET.Sdk/4.2.0">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <RootNamespace>CultivationIdle</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Shouldly" Version="4.2.1" />
  </ItemGroup>
</Project>